"""Export a single actor's next-step problem to the external Sabre planner.

No upstream source or binary is bundled. Python remains the state authority.
This exporter preserves numeric/nominal beliefs, and encodes booleans as 0/1
so that unknown Boolean information can also be represented by Sabre's `?`.
It exports only the selected NPC's actions, not the entire game or triggers.
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path
from tempfile import TemporaryDirectory

from .engine import RuleError, Session


def export_problem(session: Session, actor: str = "sun_quan") -> str:
    model = session.model
    if actor not in model.data["npc_order"]:
        raise RuleError("Sabre evaluation requires an NPC actor")
    for identifier in [actor, *model.data["facts"]]:
        if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", identifier):
            raise RuleError(f"Unsupported Sabre identifier: {identifier}")

    def term(value):
        if isinstance(value, dict):
            if "fact" in value:
                return value["fact"] + "()"
            if "parameter" in value:
                return term(model.parameters[value["parameter"]])
            if "sum" in value:
                return "(" + " + ".join(term(item) for item in value["sum"]) + ")"
        if value is None:
            return "?"
        if isinstance(value, bool):
            return str(int(value))
        if isinstance(value, int):
            return str(value)
        if isinstance(value, str) and re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", value):
            return value
        raise RuleError(f"Unsupported Sabre value: {value}")

    def condition(value):
        left, operator, right = value
        symbols = {"eq": "==", "ne": "!=", "ge": ">=", "gt": ">", "le": "<=", "lt": "<"}
        return f"{term(left)} {symbols[operator]} {term(right)}"

    actor_entity = "PlannerActor"
    lines = ["/* Generated by AlterTale; single-actor evaluation, model " + model.data["version"] + " */",
             "type symbol;", f"entity {actor_entity} : character;"]
    symbols = sorted({v for spec in model.data["facts"].values() for v in spec.get("values", [])})
    lines += [f"entity {symbol} : symbol;" for symbol in symbols]
    for key, spec in model.data["facts"].items():
        kind = "symbol" if spec["type"] == "str" else "number"
        lines.append(f"property {key}() : {kind};")
    for key, value in session.facts.items():
        lines.append(f"{key}() = {term(value)};")
        lines.append(f"believes({actor_entity}, {key}() = {term(session.beliefs[actor].get(key))});")

    for action in model.actions:
        if action["kind"] != "npc" or action["actor"] != actor:
            continue
        effects = []
        projected = {}
        for effect in action["effects"]:
            key = effect["fact"]
            value = term(effect["value"])
            if effect["operation"] == "add":
                value = f"({key}() + {value})"
            projected[key] = value
            effects.append(f"{key}() = {value}")
        effects.append(f"day() = day() + {action['days']}")
        for key in action.get("reveals", {}).get(actor, []):
            effects.append(f"believes({actor_entity}, {key}()) = {projected.get(key, key + '()')}")
        lines += [
            f"action {action['id']}() {{",
            "  precondition: " + " & ".join(condition(c) for c in action["requires"]) + ";",
            "  effect: " + " & ".join(effects) + ";",
            f"  consenting: {actor_entity};",
            "  observing(c : character): True;", "};",
        ]
    pieces = []
    for goal in model.data["actors"][actor]["goals"]:
        requirements = goal["requires"] if "requires" in goal else [goal["condition"]]
        pieces.append("(if(" + " & ".join(condition(c) for c in requirements) + f") {goal['weight']} else 0)")
    utility = " + ".join(pieces)
    lines += [f"utility(): {utility};", f"utility({actor_entity}): {utility};"]
    return "\n".join(lines) + "\n"


def run_sabre(session: Session, jar: Path, actor: str = "sun_quan") -> dict:
    if not jar.is_file():
        raise RuleError(f"Sabre JAR not found: {jar}")
    with TemporaryDirectory(prefix="altertale-sabre-") as directory:
        path = Path(directory) / "problem.txt"
        path.write_text(export_problem(session, actor), encoding="utf-8")
        try:
            result = subprocess.run(
                ["java", "-jar", str(jar.resolve()), "-p", str(path), "-tl", "5000",
                 "-atl", str(session.model.parameters["planning_depth"]), "-ctl", "2", "-el", "1"],
                text=True, capture_output=True, timeout=15,
            )
        except (OSError, subprocess.TimeoutExpired) as error:
            raise RuleError(f"Cannot run Sabre: {error}") from error
    output = result.stdout.strip()
    identifiers = {a["id"] for a in session.model.actions if a["kind"] == "npc" and a["actor"] == actor}
    plan = [name for name in re.findall(r"([A-Za-z_][A-Za-z0-9_]*)\(\)", output) if name in identifiers]
    if result.returncode or result.stderr.strip():
        raise RuleError(f"Sabre rejected the problem: {result.stderr.strip() or output}")
    # Sabre may exit successfully without finding a solution. Report that explicitly.
    return {"actor": actor, "plan": plan, "status": "found" if plan else "no_plan", "output": output}
